<section id="address__">
    <center>
        <?php if (isset($_SESSION['address_in_db'])) echo $_SESSION['address_in_db']; ?>
    <div class="address__container">
        <form class="address__form" action="includes/controllers/general.php" method="post">
        <div class="address__formContainer">
            <h2>Add address</h2>
            <div class="address__formInput">
                <label for="address_numericals">Street Number </label>
                <input type="text" name="address_numericals" value='' >
            </div>
            <br />
            <div class="address__formInput">
                <label for="address_street">Street Name </label>
                <input type="text" name="address_street" value='' >
            </div>
            <br />
            <div class="address__formInput">
                <label for="address_apt">Apartment / Lot Number </label>
                <input type="text" name="address_apt" value='' >
            </div>
            <br />
            <div class="address__formInput">
                <label for="address_city">City </label>
                <input type="text" name="address_city" value='' >
            </div>
            <br />
            <div class="address__formInput">
                <label for="address_state">Country </label>
                <select name="address_state">
                    <option value="AL">ALABAMA</option>
                    <option value="AR">ARKANSAS</option>
                    <option value="AZ">ARIZONA</option>
                    <option value="CA">CALIFORNIA</option>
                    <option value="CO">COLORADO</option>
                    <option value="CT">CONNECTICUT</option>
                    <option value="DE">DELAWARE</option>
                    <option value="DC">DISTRICT OF COLUMBIA</option>
                    <option value="FL">FLORIDA</option>
                    <option value="GA">GEORGIA</option>
                    <option value="GU">GUAM</option>
                    <option value="HI">HAWAII</option>
                    <option value="ID">IDAHO</option>
                    <option value="IL">ILLINOIS</option>
                    <option value="IN">INDIANA</option>
                    <option value="IA">IOWA</option>
                    <option value="KS">KANSAS</option>
                    <option value="LA">LOUISIANA</option>
                    <option value="ME">MAINE</option>
                    <option value="MD">MARYLAND</option>
                    <option value="MA">MASSACHUSSETTS</option>
                    <option value="MI">MICHIGAN</option>
                    <option value="MN">MINNESOTA</option>
                    <option value="MS">MISSISSIPPI</option>
                    <option value="MO">MISSOURI</option>
                    <option value="MT">MONTANA</option>
                    <option value="NE">NEBRASKS</option>
                    <option value="NV">NEVADA</option>
                    <option value="NH">NEW HAMPSHIRE</option>
                    <option value="NJ">NEW JERSEY</option>
                    <option value="NM">NEW MEXICO</option>
                    <option value="NY">NEW YORK</option>
                    <option value="NC">NORTH CAROLINA</option>
                    <option value="ND">NORTH DAKOTA</option>
                    <option value="OH">OHIO</option>
                    <option value="OK">OKLAHOMA</option>
                    <option value="OR">OREGON</option>
                    <option value="PA">PENNSYLVANIA</option>
                    <option value="PR">PUERTO RICO</option>
                    <option value="RI">RHODE ISLAND</option>
                    <option value="SC">SOUTH CAROLINA</option>
                    <option value="SD">SOUTH DAKOTA</option>
                    <option value="TN">TENESSEE</option>
                    <option value="TX">TEXAS</option>
                    <option value="UT">UTAH</option>
                    <option value="VT">VERMONT</option>
                    <option value="VI">VIRGIN ISLANDS</option>
                    <option value="VA">VIRGINIA</option>
                    <option value="WA">WASHINGTON</option>
                    <option value="WV">WEST VIRGINIA</option>
                    <option value="WI">WISCONSIN</option>
                    <option value="WY">WYOMING</option>
                </select>
            </div>
            <br />
            <div class="address__formInput">
                <label for="address_country">Country </label>
                <select name="address_country">
                    <option value="paid">USA</option>
                    <option value="paid">Canada</option>
                    <option value="paid">Mexico</option>
                </select>
            </div>
            <br />
            <div class="address__formInput">
                <label for="address_postal">Postal Code</label>
                <input type="text" name="address_postal" value='' maxlength="5" >
            </div>
            <br />
            <input type="submit" name="address__formButton">
        </div>
        </form>
    </div>
    </center>
  </section>