<section id="vehicle__">
    <center>
        <?php if (isset($_SESSION['vehicle_in_db'])) echo $_SESSION['vehicle_in_db']; ?>
    <div class="vehicle__container">
        <form class="vehicle__form" action="includes/controllers/general.php" method="post">
        <div class="vehicle__formContainer">
            <h2>Add vehicle</h2>
            <div class="vehicle__formInput">
                <label for="make">Make </label>
                <input type="text" name="make" maxlength="50" >
            </div>
            <div class="vehicle__formInput">
                <label for="vin">VIN </label>
                <input type="text" name="vin" maxlength="17" >
            </div>
            <br />
            <div class="vehicle__formInput">
                <label for="color">Street Name </label>
                <select name="color">
                    <option value="blue">blue</option>
                    <option value="red">red</option>
                    <option value="green">green</option>
                    <option value="pink">pink</option>
                    <option value="purple">purple</option>
                    <option value="orange">orange</option>
                    <option value="yellow">yellow</option>
                    <option value="silver or gold">Silver/Gold</option>
                    <option value="white">White</option>
                    <option value="black">Black</option>
                </select>
            </div>
            <br />
            <div class="vehicle__formInput">
                <label for="plate">Plate Number </label>
                <input type="text" name="plate" value='' >
            </div>
            <br />
            <div class="vehicle__formInput">
                <label for="state">State where the vehicle is registered </label>
                <select name="state">
                    <option value="AL">ALABAMA</option>
                    <option value="AR">ARKANSAS</option>
                    <option value="AZ">ARIZONA</option>
                    <option value="CA">CALIFORNIA</option>
                    <option value="CO">COLORADO</option>
                    <option value="CT">CONNECTICUT</option>
                    <option value="DE">DELAWARE</option>
                    <option value="DC">DISTRICT OF COLUMBIA</option>
                    <option value="FL">FLORIDA</option>
                    <option value="GA">GEORGIA</option>
                    <option value="GU">GUAM</option>
                    <option value="HI">HAWAII</option>
                    <option value="ID">IDAHO</option>
                    <option value="IL">ILLINOIS</option>
                    <option value="IN">INDIANA</option>
                    <option value="IA">IOWA</option>
                    <option value="KS">KANSAS</option>
                    <option value="LA">LOUISIANA</option>
                    <option value="ME">MAINE</option>
                    <option value="MD">MARYLAND</option>
                    <option value="MA">MASSACHUSSETTS</option>
                    <option value="MI">MICHIGAN</option>
                    <option value="MN">MINNESOTA</option>
                    <option value="MS">MISSISSIPPI</option>
                    <option value="MO">MISSOURI</option>
                    <option value="MT">MONTANA</option>
                    <option value="NE">NEBRASKS</option>
                    <option value="NV">NEVADA</option>
                    <option value="NH">NEW HAMPSHIRE</option>
                    <option value="NJ">NEW JERSEY</option>
                    <option value="NM">NEW MEXICO</option>
                    <option value="NY">NEW YORK</option>
                    <option value="NC">NORTH CAROLINA</option>
                    <option value="ND">NORTH DAKOTA</option>
                    <option value="OH">OHIO</option>
                    <option value="OK">OKLAHOMA</option>
                    <option value="OR">OREGON</option>
                    <option value="PA">PENNSYLVANIA</option>
                    <option value="PR">PUERTO RICO</option>
                    <option value="RI">RHODE ISLAND</option>
                    <option value="SC">SOUTH CAROLINA</option>
                    <option value="SD">SOUTH DAKOTA</option>
                    <option value="TN">TENESSEE</option>
                    <option value="TX">TEXAS</option>
                    <option value="UT">UTAH</option>
                    <option value="VT">VERMONT</option>
                    <option value="VI">VIRGIN ISLANDS</option>
                    <option value="VA">VIRGINIA</option>
                    <option value="WA">WASHINGTON</option>
                    <option value="WV">WEST VIRGINIA</option>
                    <option value="WI">WISCONSIN</option>
                    <option value="WY">WYOMING</option>
                </select>
            </div>
            <br />
            <div class="vehicle__formInput">
                <label for="engine">Engine Type</label>
                <select name="engine">
                    <option value="Gasoline">Gasoline</option>
                    <option value="Diesel">Diesel</option>
                    <option value="Hybrid">Hybrid</option>
                    <option value="Electric">Electric</option>
                </select>
            </div>
            <br />
            <div class="vehicle__formInput">
                <label for="type">Vehicle Type</label>
                <select name="type">
                    <option value="SUV">SUV</option>
                    <option value="Car">Car</option>
                    <option value="Truck">Truck</option>
                    <option value="Motorcycle">Motorcycle</option>
                </select>
            </div>
            <br />
            <div class="vehicle__formInput">
                <label for="insured">Insured</label>
                <select name="insured">
                    <option value="insured">insured</option>
                    <option value="not_insured">not_insured</option>
                </select>
            </div>
            <input type="submit" name="vehicle__formButton">
        </div>
        </form>
    </div>
    </center>
  </section>